version: "3.8"

services:
  backend: 
    container_name: zoe-fastapi
    labels:
      - com.host.description= fastapi backend for zoe
    build: .
    expose:
      - 8000
    ports: 
      - "9000:8000"
      - "5432:5432"
    working_dir: /app
    restart: on-failure

#   database: 
#     container_name: zoe-postgres-db
#     labels:
#       - com.host.description= database for zoe
#     image: postgres:14.5-bullseye
#     environment:
#       - POSTGRES_USER=zoe-postgres
#       - POSTGRES_PASSWORD=Afolarin1
#     expose:
#       - 5432
#     ports:
#       - "5432:5432"
#     restart: on-failure
#     volumes:
#       - db-data:/var/lib/postgresql/data

# volumes:
#   database:
#     driver: local
